#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# deb-repo-manager.sh — DEB repository management and publishing
# ─────────────────────────────────────────────────────────────────────────────
#
# Creates and manages Debian/Ubuntu package repositories with proper Packages
# and Release metadata. Supports signing and publishing to remote locations.
#
# Usage:
#   ./deb-repo-manager.sh init <REPO_DIR>
#   ./deb-repo-manager.sh add <DEB_FILE> <DISTRIBUTION>
#   ./deb-repo-manager.sh organize <SOURCE_DIR> <REPO_DIR>
#   ./deb-repo-manager.sh publish <REPO_DIR> <DEST_URL>
#   ./deb-repo-manager.sh generate-release <REPO_DIR>
#
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# Configuration
SIGN_REPO="${SIGN_REPO:-0}"
GPG_KEY_ID="${GPG_KEY_ID:-}"

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[✓]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[✗]${NC} $*"; }

# ─── Initialize DEB repository structure ──────────────────────────────────────
init_repo() {
    local repo_dir="$1"
    
    log_info "Initializing DEB repository at: $repo_dir"
    
    mkdir -p "$repo_dir"
    
    # Create standard Debian repository structure
    for codename in bookworm bullseye trixie sid noble jammy jammy focal mantic oracular; do
        local dist_dir="$repo_dir/$codename/pool/main"
        mkdir -p "$dist_dir"
        
        # Create directory stubs for each letter (a-z)
        for letter in {a..z}; do
            mkdir -p "$dist_dir/$letter"
        done
    done
    
    # Create metadata directory
    mkdir -p "$repo_dir/dists"
    
    log_success "Repository structure initialized"
    
    # Create default configuration file
    cat > "$repo_dir/.repo-config" << CONF
# DEB Repository Configuration
# Generated by deb-repo-manager.sh

REPO_DIR="$repo_dir"
SIGN_REPO=$SIGN_REPO
GPG_KEY_ID="$GPG_KEY_ID"

# Supported distributions
DISTRIBUTIONS=(
    "bookworm"
    "bullseye"
    "trixie"
    "sid"
    "noble"
    "jammy"
    "focal"
    "mantic"
    "oracular"
)

# Architecture support
ARCHITECTURES=("amd64" "arm64" "i386")

CONF
    
    log_success "Repository configuration created"
}

# ─── Add package to repository ────────────────────────────────────────────────
add_package() {
    local deb_file="$1"
    local distribution="$2"
    local repo_dir="${3:-.}"
    
    if [[ ! -f "$deb_file" ]]; then
        log_error "Package not found: $deb_file"
        return 1
    fi
    
    log_info "Adding package to repository: $(basename "$deb_file")"
    
    # Extract metadata from DEB file
    local package_name
    local arch
    package_name=$(dpkg-deb -f "$deb_file" Package)
    arch=$(dpkg-deb -f "$deb_file" Architecture)
    
    # Get first letter for pool organization
    local first_letter="${package_name:0:1}"
    
    # Create pool directory
    local pool_dir="$repo_dir/$distribution/pool/main/$first_letter/$package_name"
    mkdir -p "$pool_dir"
    
    # Copy package to repository
    cp -p "$deb_file" "$pool_dir/"
    
    log_success "Package added to: $distribution/pool/main/$first_letter/$package_name/"
}

# ─── Organize packages from source to repository ──────────────────────────────
organize_packages() {
    local source_dir="$1"
    local repo_dir="$2"
    
    log_info "Organizing packages from: $source_dir"
    
    if [[ ! -d "$source_dir" ]]; then
        log_error "Source directory not found: $source_dir"
        return 1
    fi
    
    # Find all .deb files
    local count=0
    find "$source_dir" -name "*.deb" -type f | while read -r deb_file; do
        # Try to determine distribution from directory structure
        local distro=""
        
        # Look for distribution in path: /builds/<builder>/<distro>/
        if [[ $deb_file =~ /builds/[^/]+/([^/]+)/ ]]; then
            distro="${BASH_REMATCH[1]}"
        fi
        
        # Try newer mapping: /builds/docker/bookworm/DEBS/
        if [[ -z "$distro" && $deb_file =~ /([a-z]+)/DEBS/ ]]; then
            distro="${BASH_REMATCH[1]}"
        fi
        
        if [[ -n "$distro" ]]; then
            log_info "Found package for distribution: $distro"
            add_package "$deb_file" "$distro" "$repo_dir"
            ((count++))
        else
            log_warn "Could not determine distribution for: $(basename "$deb_file")"
        fi
    done
    
    log_success "Organized $count packages"
}

# ─── Generate Packages and Release metadata ───────────────────────────────────
generate_release() {
    local repo_dir="$1"
    
    log_info "Generating repository metadata..."
    
    if [[ ! -d "$repo_dir" ]]; then
        log_error "Repository directory not found: $repo_dir"
        return 1
    fi
    
    # Generate Packages file for each distribution
    for dist_dir in "$repo_dir"/*/pool/main; do
        if [[ ! -d "$dist_dir" ]]; then
            continue
        fi
        
        local distro=$(basename "$(dirname "$dist_dir")")
        local dists_dir="$repo_dir/dists/$distro"
        
        mkdir -p "$dists_dir/main/binary-amd64"
        mkdir -p "$dists_dir/main/binary-arm64"
        
        log_info "Generating Packages for $distro..."
        
        # Create Packages file
        apt-ftparchive packages "$dist_dir" > "$dists_dir/main/binary-amd64/Packages"
        gzip -9k "$dists_dir/main/binary-amd64/Packages"
        
        # Create Release file
        cat > "$dists_dir/Release" << RELEASE_HEADER
Suite: $distro
Codename: $distro
Date: $(date -Ru)
Architectures: amd64 arm64
Components: main
Description: PostgreSQL Debian Repository - $distro
Label: PostgreSQL
Origin: pg-platform

RELEASE_HEADER
        
        log_success "Generated Packages and Release for $distro"
    done
    
    log_success "Repository metadata generation completed"
}

# ─── Sign Release files ───────────────────────────────────────────────────────
sign_release() {
    local repo_dir="$1"
    
    if [[ "$SIGN_REPO" -ne 1 ]]; then
        log_info "Repository signing disabled"
        return 0
    fi
    
    if [[ -z "$GPG_KEY_ID" ]]; then
        log_error "GPG_KEY_ID not set. Cannot sign repository."
        return 1
    fi
    
    log_info "Signing Release files with key: $GPG_KEY_ID"
    
    for release_file in "$repo_dir"/dists/*/Release; do
        if [[ -f "$release_file" ]]; then
            log_info "Signing: $release_file"
            gpg --default-key "$GPG_KEY_ID" \
                --armor \
                --sign \
                --detach-sign \
                "$release_file"
            
            log_success "Signed: $release_file"
        fi
    done
}

# ─── Publish repository to remote location ────────────────────────────────────
publish_repo() {
    local repo_dir="$1"
    local dest_url="$2"
    
    log_info "Publishing repository to: $dest_url"
    
    if [[ ! -d "$repo_dir" ]]; then
        log_error "Repository directory not found: $repo_dir"
        return 1
    fi
    
    case "$dest_url" in
        s3://*)
            publish_to_s3 "$repo_dir" "$dest_url"
            ;;
        http://*|https://*)
            publish_via_rsync "$repo_dir" "$dest_url"
            ;;
        /*|./*|~*)
            publish_local "$repo_dir" "$dest_url"
            ;;
        *)
            log_error "Unsupported destination: $dest_url"
            return 1
            ;;
    esac
}

# ─── Publish to S3 ───────────────────────────────────────────────────────────
publish_to_s3() {
    local repo_dir="$1"
    local s3_url="$2"
    
    if ! command -v aws &> /dev/null; then
        log_error "AWS CLI not found. Install with: pip install awscli"
        return 1
    fi
    
    log_info "Uploading to S3: $s3_url"
    
    aws s3 sync \
        --delete \
        --cache-control "max-age=3600" \
        "$repo_dir/" "$s3_url/" \
        --exclude ".repo-config"
    
    log_success "S3 publish completed"
}

# ─── Publish via rsync ────────────────────────────────────────────────────────
publish_via_rsync() {
    local repo_dir="$1"
    local dest="$2"
    
    if ! command -v rsync &> /dev/null; then
        log_error "rsync not found. Install with: apt-get install rsync"
        return 1
    fi
    
    log_info "Syncing to: $dest"
    
    rsync -avz \
        --delete \
        --exclude ".repo-config" \
        "$repo_dir/" "$dest/"
    
    log_success "Rsync publish completed"
}

# ─── Publish to local filesystem ──────────────────────────────────────────────
publish_local() {
    local repo_dir="$1"
    local dest_dir="$2"
    
    log_info "Copying to local directory: $dest_dir"
    
    mkdir -p "$dest_dir"
    
    cp -rv \
        --exclude ".repo-config" \
        "$repo_dir"/* "$dest_dir/"
    
    log_success "Local publish completed"
}

# ─── Show help ────────────────────────────────────────────────────────────────
show_help() {
    cat << 'HELP'
DEB Repository Manager

USAGE:
  deb-repo-manager.sh <command> [options]

COMMANDS:
  init <REPO_DIR>
    Initialize repository structure in REPO_DIR

  add <DEB_FILE> <DISTRIBUTION> [REPO_DIR]
    Add a single package to the repository
    DISTRIBUTION: codename (bookworm, noble, jammy, etc.)

  organize <SOURCE_DIR> <REPO_DIR>
    Organize packages from SOURCE_DIR into REPO_DIR
    Automatically determines distribution from directory structure

  generate-release <REPO_DIR>
    Generate Packages and Release metadata files
    Must be done before publishing repository

  publish <REPO_DIR> <DEST_URL>
    Publish repository to destination (S3, rsync, or local)
    Examples:
      s3://my-bucket/deb
      remote.host:/var/www/deb
      /var/www/html/deb

  sign <REPO_DIR>
    Sign Release files with GPG key

  help
    Show this help message

ENVIRONMENT VARIABLES:
  SIGN_REPO              Enable repository signing (0 or 1) [default: 0]
  GPG_KEY_ID             GPG key ID for signing
  AWS_PROFILE            AWS profile for S3 operations

EXAMPLES:
  # Create new repository
  ./deb-repo-manager.sh init /tmp/deb-repo

  # Add package
  ./deb-repo-manager.sh add postgresql-16_16.0-1_amd64.deb bookworm /tmp/deb-repo

  # Organize built packages
  ./deb-repo-manager.sh organize output/builds/docker /tmp/deb-repo

  # Generate metadata
  ./deb-repo-manager.sh generate-release /tmp/deb-repo

  # Publish to S3
  ./deb-repo-manager.sh publish /tmp/deb-repo s3://my-bucket/deb

REQUIREMENTS:
  apt-ftparchive (apt-utils package)
  gpg (for signing, optional)
  aws (for S3 publishing, optional)
  rsync (for rsync publishing, optional)

REPOSITORY STRUCTURE:
  repo_dir/
  ├── bookworm/pool/main/
  │   ├── a/..., b/..., ..., z/
  │   └── [packages organized by first letter]
  ├── noble/pool/main/
  │   ├── a/..., b/..., ..., z/
  │   └── [packages organized by first letter]
  ├── dists/
  │   ├── bookworm/
  │   │   ├── Release
  │   │   ├── Release.gpg
  │   │   └── main/binary-amd64/Packages.gz
  │   └── noble/...
  └── .repo-config

HELP
}

# ─── Main command dispatcher ──────────────────────────────────────────────────
main() {
    local command="${1:-help}"
    shift || true
    
    case "$command" in
        init)
            if [[ $# -lt 1 ]]; then
                log_error "init requires repository directory argument"
                return 1
            fi
            init_repo "$1"
            ;;
        
        add)
            if [[ $# -lt 2 ]]; then
                log_error "add requires package file and distribution arguments"
                return 1
            fi
            add_package "$1" "$2" "${3:-.}"
            ;;
        
        organize)
            if [[ $# -lt 2 ]]; then
                log_error "organize requires source and repository directory arguments"
                return 1
            fi
            organize_packages "$1" "$2"
            ;;
        
        generate-release)
            if [[ $# -lt 1 ]]; then
                log_error "generate-release requires repository directory argument"
                return 1
            fi
            generate_release "$1"
            ;;
        
        sign)
            if [[ $# -lt 1 ]]; then
                log_error "sign requires repository directory argument"
                return 1
            fi
            sign_release "$1"
            ;;
        
        publish)
            if [[ $# -lt 2 ]]; then
                log_error "publish requires repository and destination arguments"
                return 1
            fi
            generate_release "$1"  # Ensure metadata is current
            publish_repo "$1" "$2"
            ;;
        
        help|--help|-h)
            show_help
            ;;
        
        *)
            log_error "Unknown command: $command"
            show_help
            return 1
            ;;
    esac
}

main "$@"
